{
					"DATABASE": "impala",
					"INSTANCE": "CCN",
					"HOST": "10.128.164.51",
					"PORT": "21050",
					"USER": "apps",
					"PASSWORD": "4pps1sat",
					"QUERY" : "SELECT TRANSACTION_DATE,SERVICE_TYPE, SUM(CAST(TOTAL_AMOUNT AS DOUBLE)) AS TOTAL_AMOUNT, SUM(CAST(TOTAL_HIT AS DOUBLE)) AS TOTAL_HIT FROM CCN.DTL_REV_COMPONENT  WHERE REVENUE_FLAG = 'Yes' GROUP BY TRANSACTION_DATE, SERVICE_TYPE ORDER BY TRANSACTION_DATE, SERVICE_TYPE",
					"OUTFILE": "filename.dat",
					"DELIMITER": "|"
					}

